package archivosjava;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

public class Main extends javax.swing.JFrame {

    File archivo;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fc = new javax.swing.JFileChooser();
        VentanaDatos = new javax.swing.JFrame();
        NombreLabel = new javax.swing.JLabel();
        GuardarDatosButton = new javax.swing.JButton();
        NombreTextField = new javax.swing.JTextField();
        CodigoTextField = new javax.swing.JTextField();
        NotaTextField = new javax.swing.JTextField();
        CodigoLabel = new javax.swing.JLabel();
        NotaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GuardarButton = new javax.swing.JButton();
        AñadirButton = new javax.swing.JButton();
        SeleccionarButton = new javax.swing.JButton();
        ArchivoTextField = new javax.swing.JTextField();
        btnborrar = new javax.swing.JButton();

        VentanaDatos.setMinimumSize(new java.awt.Dimension(250, 193));

        NombreLabel.setText("Nombre");

        GuardarDatosButton.setText("Guardar");
        GuardarDatosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarDatosButtonActionPerformed(evt);
            }
        });

        CodigoLabel.setText("Código");

        NotaLabel.setText("Nota");

        javax.swing.GroupLayout VentanaDatosLayout = new javax.swing.GroupLayout(VentanaDatos.getContentPane());
        VentanaDatos.getContentPane().setLayout(VentanaDatosLayout);
        VentanaDatosLayout.setHorizontalGroup(
            VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaDatosLayout.createSequentialGroup()
                .addGroup(VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(NombreTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                            .addComponent(NotaTextField))
                        .addGroup(VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaDatosLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(CodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VentanaDatosLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(CodigoLabel))
                            .addGroup(VentanaDatosLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(GuardarDatosButton))))
                    .addGroup(VentanaDatosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(NotaLabel)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        VentanaDatosLayout.setVerticalGroup(
            VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(VentanaDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NotaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarDatosButton))
                .addGap(67, 67, 67))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        GuardarButton.setText("Guardar");
        GuardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarButtonActionPerformed(evt);
            }
        });

        AñadirButton.setText("Añadir");
        AñadirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirButtonActionPerformed(evt);
            }
        });

        SeleccionarButton.setText("Seleccionar");
        SeleccionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarButtonActionPerformed(evt);
            }
        });

        ArchivoTextField.setEditable(false);

        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AñadirButton)
                .addGap(36, 36, 36)
                .addComponent(btnborrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GuardarButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ArchivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SeleccionarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionarButton)
                    .addComponent(ArchivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarButton)
                    .addComponent(AñadirButton)
                    .addComponent(btnborrar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirButtonActionPerformed
       CodigoTextField.setText("");
       NombreTextField.setText("");
       NotaTextField.setText("");
       
       //mostrar ventana agregar datos
        VentanaDatos.setVisible(true);
    }//GEN-LAST:event_AñadirButtonActionPerformed

    private void GuardarDatosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarDatosButtonActionPerformed
        String nombre = NombreTextField.getText();
        String codigo = CodigoTextField.getText();
        double nota = Double.parseDouble(NotaTextField.getText()); //convierte la nota string a double
        
        //obtener modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object [] { codigo, nombre, nota  }); // se escribe en el mismo orden de la tabla en el main. Se añaden datos a la tabla
        
        VentanaDatos.setVisible(false);
    }//GEN-LAST:event_GuardarDatosButtonActionPerformed

    private void SeleccionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarButtonActionPerformed
        //Añadir un filtro
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos txt", "txt");
        
        //Agregar filtro al selector de archivos
        fc.setFileFilter(filter);
        
        //Abrir la ventana del selector
        
        int opcion = fc.showOpenDialog(this);
        
        //si el usuario acepto
        if(opcion == JFileChooser.APPROVE_OPTION){
            
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.setRowCount(0); //eliminar filas de la tabla
             
            archivo = fc.getSelectedFile();
            ArchivoTextField.setText(archivo.getAbsolutePath());
            try(Scanner scan = new Scanner(archivo)){
                while (scan.hasNextLine()){
                    String linea = scan.nextLine();
                    String [] datos = linea.split(","); //cuando encuentre una coma, agrega al vector
                    
                   
                    model.addRow(new Object []{
                        datos[0],  //codigo
                        datos[1],  //nombre
                        Double.parseDouble(datos[2])  //nota
                    });
                }
            } catch(IOException ex){
                //TODO Mostrar error
                mostrarError("Error"," Ha ocurrido un error");
            } catch(Exception ex){
                //TODO Mostrar error
                mostrarError("Error"," Ha ocurrido un error");
            }
        }
    }//GEN-LAST:event_SeleccionarButtonActionPerformed

    private void GuardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarButtonActionPerformed
        if(archivo != null){
            try {
                BufferedWriter writer = new BufferedWriter(new FileWriter(archivo));
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                int filas= model.getRowCount();
                
                for (int i = 0; i < filas; i++) {
                    String codigo= (String) model.getValueAt(i, 0);
                    String nombre= (String) model.getValueAt(i, 1);
                    Double nota = (Double) model.getValueAt(i,2);
                    String linea = codigo + ","+ nombre + "," +nota;
                    writer.write(linea);
                    writer.newLine();
                }
                writer.close();
            } catch (IOException ex) {
               //TODO Mostrar error
                   mostrarError("Error"," Ha ocurrido un error");
            }
        }else{
            //TODO Mostrar error
                mostrarError("Error"," Ha ocurrido un error");
        }
    }//GEN-LAST:event_GuardarButtonActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        //Borrar datos
        try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int i= jTable1.getSelectedRow();
        model.removeRow(i);
        }catch(ArrayIndexOutOfBoundsException ex){
                mostrarError("Error"," Ha ocurrido un error");
        }
    }//GEN-LAST:event_btnborrarActionPerformed
    void mostrarError(String titulo, String descrip){
        JOptionPane.showMessageDialog(this,descrip, titulo, JOptionPane.ERROR_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArchivoTextField;
    private javax.swing.JButton AñadirButton;
    private javax.swing.JLabel CodigoLabel;
    private javax.swing.JTextField CodigoTextField;
    private javax.swing.JButton GuardarButton;
    private javax.swing.JButton GuardarDatosButton;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTextField;
    private javax.swing.JLabel NotaLabel;
    private javax.swing.JTextField NotaTextField;
    private javax.swing.JButton SeleccionarButton;
    private javax.swing.JFrame VentanaDatos;
    private javax.swing.JButton btnborrar;
    private javax.swing.JFileChooser fc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
